### ISSUE TITLE
Page creation dialog needs to have title and description 

### ISSUE THREAD

**Issue by andyburnett** [Knowinnovation/KiStorm#11]
The title would appear in the menu (maybe truncated so it doesn't take too much of the menu - take a look at the latest example page I added), and the title and description would appear at the top of the page.

The description gives us an option to explain more about what it is we're meant to be brainstorming about. The title is the question.

**Comment by drewsdunne** [comment]
I'm not sure I understand what you mean, and I don't see the example page...

**Comment by andyburnett** [comment]
The example page starts "what are all the ways we could..."

It looks too long on the menu.

**Comment by andyburnett** [comment]
So, we need a way of truncating it in the menu, and also a field in the dialog box to let us write more of a description.
