### ISSUE TITLE
Rename Workshops to Pages

### ISSUE THREAD

**Issue by andyburnett** [Knowinnovation/KiStorm#3]
I think our data hierarchy should be

Group
  Event
    Page(s)

So, we can have multiple events within a group, and within each event there can be multiple diverge and converge pages

**Comment by drewsdunne** [comment]
Sounds fine to me. I'm not really sure what you're defining as a group and an event. But right now we if you create a group on the hub, it uses that group id as the database reference and stores all the "workshops" or pages in there.

**Comment by andyburnett** [comment]
It was David's comment that set me thinking about this.  A group would be a collection of people who - might - hold one or more events.  We could create a different hub group for each event, but it would make more sense to have a single group, and then set up an 'event' kiapps page for each event.

The kiapps page would contain a KiStorm app. The app could then contain multiple pages for that particular event.  And now, looking at it, I realise that we are using the term page in too many places. We should talk about the hub 'page' as being a menu item, and the KiStorm pages as pages.

**Comment by drewsdunne** [comment]
Whoa, lot's of pages being thrown around here. I'm having a little trouble following. So in the Hub group, we want each page in there to correspond to a new KiStorm pages/workshops database. If that's the case, then we'll just need to change the init script that we are using to pass in some sort of hub page id rather than the group id.

**Comment by andyburnett** [comment]
No, we are definitely suffering from page overload!

In summary, if you change Workshop to Page, we are good ;-)

**Comment by drewsdunne** [comment]
Sounds good to me, already done on my local version.
