### ISSUE TITLE
Selecting a page shouldn't require a second click

### ISSUE THREAD

**Issue by andyburnett** [Knowinnovation/KiStorm#5]
Clicking the page name changes the underlying page, but doesn't remove the menu. You have to click on the lightbox to remove the menu

**Comment by drewsdunne** [comment]
Right, I can add this feature in.

**Comment by andyburnett** [comment]
Doesn't seem to be fixed in the demo version I am using.

**Comment by drewsdunne** [comment]
Demo isn't updated, just master

**Comment by andyburnett** [comment]
Ah, that's what I wondered. Ok, can you push to the demo branch, or is there a way for me to do that?

**Comment by drewsdunne** [comment]
Yes I can, I’m just about to make one more change and then I’ll push that. 

---------------
Drew Dunne
drew@drewsdunne.com

**Comment by drewsdunne** [comment]
Try it now

---------------
Drew Dunne
drew@drewsdunne.com

**Comment by andyburnett** [comment]
Excellent,

That works much better. I did notice on load up it's still talks about workshops, so I think there is a string in there that needs to be changed.

I'm really impressed with the quality of what polymer let's us billed. I know it's a bit of a pain but the overall look and feel is great.

**Comment by drewsdunne** [comment]
Right I see that, let me fix it. And yeah, it took some work but the apps end up looking very nice and Google-like.
