### ISSUE TITLE
Displaying entries in a single column looks best

### ISSUE THREAD

**Issue by andyburnett** [Knowinnovation/KiStorm#6]
Having played with it, I think the multi-column layout is harder to read and understand. A simple single column list is best

**Comment by drewsdunne** [comment]
alright, do you want them to fill the majority of the page or would you like a fixed max-width.

**Comment by andyburnett** [comment]
I actually like the fixed width view.  It encourages brevity!

**Comment by drewsdunne** [comment]
I thought so too! Also at a certain width the cards stop looking like cards and look more like horribly designed windows so best to fix the width at a certain point!
