### ISSUE TITLE
Can we change the + symbol to a check mark?

### ISSUE THREAD

**Issue by andyburnett** [Knowinnovation/KiStorm#8]
I think the + sign on the new entry box is slightly confusing. I think it might be better if there was nothing present until something was typed, and then a check mark appeared to allow saving.

**Comment by drewsdunne** [comment]
That's doable, but how is the plus sign confusing exactly?

**Comment by andyburnett** [comment]
I think it is because the plus sign is signifying two things, add a new item and save the item. 

When one edits an item the pen turns to a check mark to show save. I think it would be clearer if it did that in the main input box too - instead of the plus sign

**Comment by drewsdunne** [comment]
I've changed this, but to me it seems extremely unintuitive. Especially because you have to click off the input for the button to appear.

**Comment by andyburnett** [comment]
Yes, I agree. It isn't right, yet. We need to do more experiments.
